# Path to oh-my-zsh installation.
export ZSH=$HOME/dotfiles/oh-my-zsh

# Explicitly set XDG_CONFIG_HOME environment variable to encourage anything searching for config to look here first.
export XDG_CONFIG_HOME="$HOME/.config"

# Enable command auto-correction.
ENABLE_CORRECTION=true

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
#
# vi-mode goes first as it can otherwise override things that break other plugins
plugins=(vi-mode command-not-found composer docker docker-compose fzf git history-substring-search last-working-dir tmux fzf-tab)

export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH

# Look for additional completions
fpath=($HOME/dotfiles/zsh/completions/ $fpath)

#####
# In general, all ZSH_* variables for controlling oh-my-zsh behaviour need to be set before sourcing oh-my-zsh.sh
#####

# Set location for custom themes and plugins
ZSH_CUSTOM=$HOME/dotfiles/zsh_custom

# Use spaceship prompt
SPACESHIP_TIME_SHOW=true
SPACESHIP_BATTERY_SHOW=false
ZSH_THEME="spaceship"

# Automatically start tmux when opening a new terminal window (window will also automatically close when exiting tmux)
ZSH_TMUX_AUTOSTART=true
# Don't autoconnect to previous tmux session (if one exists) when opening new terminal window. Autoconnecting prevents
# me from having multiple windows with different tmux sessions for different things and that's just annoying
ZSH_TMUX_AUTOCONNECT=false

# When searching history, ignore adjacent duplicates
setopt HIST_FIND_NO_DUPS

source $ZSH/oh-my-zsh.sh

# Make Vi mode transitions faster (KEYTIMEOUT is in hundredths of a second, default is 40 so 0.4 seconds)
export KEYTIMEOUT=1

export LANG=en_GB.UTF-8

# Make neovim the default editor
export VISUAL='nvim'

# Set a global config file for ripgrep (rg)
export RIPGREP_CONFIG_PATH="$HOME/dotfiles/misc/ripgreprc"

# Set the path to the bat config file
export BAT_CONFIG_PATH="$HOME/dotfiles/misc/bat.conf"

# Use fd rather than find as it is faster. Respect any .ignore files (but not VCS ignore such as .gitignore)
export FZF_DEFAULT_COMMAND='fd --type=file --strip-cwd-prefix --no-ignore-vcs --hidden --ignore-case'

# Set default FZF options
# - layout=reverse causes FZF to list top to bottom rather than bottom to top
# - bind overrides the default bindings to scroll the preview window up/down
export FZF_DEFAULT_OPTS="--layout=reverse --bind ctrl-alt-k:preview-up,ctrl-alt-j:preview-down,ctrl-alt-l:preview-page-up,ctrl-alt-h:preview-page-down"

# Set up fnm (--use-on-cd auto-switches to the right version when a directory contains a .node-version or .nvmrc file)
eval "$(fnm env --use-on-cd)"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
alias grep='grep --color=always' # Always colour highlight matching strings with grep
alias lesss='less -r' # Output raw control characters (maintains colours etc when piping through less)
alias sedhelp='echo "rg --files-with-matches --color=never SEARCH_TERM [PATHS] | xargs sed -i '\''s/SEARCH_TERM/REPLACEMENT/g'\''"'
alias rmswp='rm ~/.local/state/nvim/swap/*'
alias fzfp="fzf --preview '(bat --color=always {} || cat {})'"
alias vi='nvim'
alias vim='nvim'
alias gcf='git status --porcelain | cut -c 1-3 --complement | xargs' # List all changed files (staged and unstaged) on a single line
alias apt='echo -e "\n\nCOULD YOU USE nala INSTEAD?\n\n" && apt'
# Makes all aliases also work when running as root
alias sudo='sudo '
